<?php
/**
 * Creates and activates a draft FUL LMS Privacy Policy via Moodle's Site Policy feature
 * (tool_policy). This is placeholder content for a final year project/prototype - it has
 * NOT been reviewed by a lawyer or a Data Protection Officer, and must be reviewed and
 * formally adopted before real students' personal data is processed in production.
 *
 * Usage: php local/fulokoja_lms/cli/create_privacy_policy.php
 */

define('CLI_SCRIPT', true);
require(__DIR__ . '/../../../config.php');
require_once($CFG->dirroot . '/admin/tool/policy/classes/api.php');

global $DB;
\core\session\manager::set_user(reset(get_admins()));

use tool_policy\api;
use tool_policy\policy_version;

$privacycontent = <<<'HTML'
<p><em>This is a placeholder policy prepared for a final year academic project/prototype. It has not been reviewed by a lawyer or a Data Protection Officer, and must be reviewed and formally adopted before this system is used with real students' personal data in production.</em></p>

<h3>What this policy covers</h3>
<p>This privacy policy explains how the Federal University Lokoja Integrated Learning Management System (FUL LMS) collects, uses, and protects personal data, in line with the Nigeria Data Protection Act, 2023 (NDPA) and the Discrimination Against Persons with Disabilities (Prohibition) Act, 2018.</p>

<h3>What we collect</h3>
<ul>
<li>Account information: name, email address, matriculation/staff number, and role (student, lecturer, or administrator).</li>
<li>Academic activity: course enrolments, assignment submissions, grades, quiz/exam attempts, and messages sent within the platform.</li>
<li>Accessibility preferences you choose to set (screen reader mode, text size, high contrast, caption defaults) - these are used only to personalise your own experience.</li>
<li>Technical data automatically generated by using the site: login timestamps and basic activity logs, used for security and to keep the gradebook and accessibility compliance reporting accurate.</li>
</ul>

<h3>Why we collect it</h3>
<p>Solely to deliver the core educational service: enrolling you in courses, tracking your submissions and grades, enabling communication with lecturers/classmates, and (for administrators) reporting on accessibility compliance and platform usage as described in this project's objectives.</p>

<h3>Where it's stored</h3>
<p>Data is stored in a managed database on this platform's hosting provider. As a class project/prototype, this may currently be outside Nigeria; a production deployment for FUL would need this confirmed and, if applicable, handled in line with the NDPA's cross-border data transfer requirements.</p>

<h3>Who can see it</h3>
<p>Your lecturers can see your submissions, grades, and course activity for courses you're enrolled in. Administrators can see platform-wide usage and accessibility compliance reports. Nobody outside the platform's administrators and your own lecturers has access to your personal data.</p>

<h3>Your rights</h3>
<p>You can ask to see what personal data is held about you, ask for corrections, or ask questions about this policy by contacting the system administrator.</p>
HTML;

$policy = new stdClass();
$policy->name = 'FUL LMS Privacy Policy';
$policy->type = policy_version::TYPE_PRIVACY;
$policy->audience = policy_version::AUDIENCE_ALL;
$policy->agreementstyle = policy_version::AGREEMENTSTYLE_CONSENTPAGE;
$policy->optional = policy_version::AGREEMENT_COMPULSORY;
$policy->revision = 'v1 (draft - pending legal review)';
$policy->summary_editor = ['text' => '<p>How FUL LMS collects, uses, and protects your personal data.</p>', 'format' => FORMAT_HTML, 'itemid' => 0];
$policy->content_editor = ['text' => $privacycontent, 'format' => FORMAT_HTML, 'itemid' => 0];

$existing = $DB->get_record('tool_policy', ['id' => $DB->get_field_sql(
    "SELECT tp.id FROM {tool_policy} tp JOIN {tool_policy_versions} tpv ON tpv.policyid = tp.id WHERE tpv.name = ?",
    [$policy->name]
)]);

if (!$existing) {
    $version = api::form_policydoc_add($policy);
    api::make_current($version->get('id'));
    echo "Created and activated FUL LMS Privacy Policy (version id={$version->get('id')}).\n";
} else {
    echo "Privacy policy already exists (policy id={$existing->id}) - skipping.\n";
}

set_config('sitepolicyhandler', 'tool_policy');
purge_all_caches();
echo "Enabled tool_policy as the site policy handler.\n";
